---
spring:
  data:
    rest:
      base-path: crud
  jpa:
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

allowedOrigins: "*"

---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  profiles: local
  datasource:
    # url specifies a file name, appended with ".mv.db"
    # jdbc:h2:{filename}
    url: 
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      # use this to create an h2-only sql admin console within the application
      enabled: true
      # go to http://{host}/{path} to see the sql admin console
      path: /h2-console

---
spring:
  profiles: pcf-qa

---
spring:
  profiles: pcf-prod
allowedOrigins: "*"

---
spring:
  profiles: heroku
allowedOrigins: "*"
